### ISSUE TITLE
Cannot import existing resources without providing the exact required field values

### ISSUE THREAD

**Issue by ezgidemirel** [upbound/upjet#2]
### What happened?

Tried to import an existing subnet resource in provider-jet-aws with following manifest:
```
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  annotations:
    crossplane.io/external-name: subnet-03c0119e7ed0b4847
  name: ezgi-subnet
spec:
  forProvider:
    region: us-west-1
    cidrBlock: ""
    vpcId: ""
```

`cidrBlock` and `vpcId` fields are required and need to be provided for schema validation. However, passing empty values to those resources causes the following error:
```
Warning  CannotObserveExternalResource  19s (x5 over 31s)  managed/ec2.aws.jet.crossplane.io/v1alpha2, kind=subnet  cannot run refresh: refresh failed: Missing required argument: The argument "vpc_id" is required, but no definition was found.: File name: main.tf.json
```

Importing a subnet resource is possible by Terraform with only external-name info (please see [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#import) for more information). Therefore, the manifest above should work. 

This use case is especially important for customers who will migrate from native providers to jet providers. 

### How can we reproduce it?

Create a subnet resource with the following manifest:
```
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: ezgi-subnet
spec:
  deletePolicy: Orphan
  forProvider:
    region: us-west-1
    availabilityZone: us-west-1b
    vpcIdRef:
      name: ezgi-vpc
    cidrBlock: 172.16.10.0/24
```
Delete the MR and try to import it with the first manifest.
