### ISSUE TITLE
Migration should notify of skipped resources

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/upjet#245]
### What problem are you facing?

When creating a migration on a local filesystem if a file contains unknown Kinds, the migrator will not process the file silently. 

For example, if a manifest contains a `Secret`, outputs are never generated.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-foo-mq-rabbitmq-creds
  namespace: example
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
immutable: true
data:
  password: "cGFzc3dvcmQK"
---
apiVersion: mq.aws.crossplane.io/v1alpha1
kind: Broker
metadata:
  labels:
    crossplane.io/provider-version: v0.26.1
  name: demo-foo-mq-rabbitmq
  namespace: example
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  forProvider:
    region: us-east-1
    engineType: RabbitMQ
    publiclyAccessible: false
    autoMinorVersionUpgrade: false
    engineVersion: 3.8.11
    hostInstanceType: mq.t3.micro
    deploymentMode: SINGLE_INSTANCE
    subnetIDs:   
      - subnet-2cc5ce61
    securityGroupIdRefs:
      - name: demo-foo-mq-rabbitmq-security-group
    users:
      - username: rabbitmq-admin
        consoleAccess: true
        passwordSecretRef:
          key: password
          name: demo-foo-mq-rabbitmq-creds
          namespace: example
    tags:
      App: crossplane
      Environment: qa
      Name: crossplane-mq
      Product: crossplane
      Squad: sandbox
      Tier: backend
      VS: sandbox
      cluster: mq-cluster
  writeConnectionSecretToRef:
    name: demo-foo-mq-creds
    namespace: example
  providerConfigRef:
    name: awsconfig

```

The generated migration plan is mostly empty and none of the other directories are crated. 

```yaml
spec: {}
version: 0.1.0
```

### How could Upjet help solve your problem?

The user should be informed of any local filesystem resources that have been skipped during processing.
