### ISSUE TITLE
Misleading error pointing to spec.initProvider when required parameters are not provided

### ISSUE THREAD

**Issue by turkenh** [upbound/upjet#273]
### What happened?

We are getting misleading/confusing errors when we don't provide a top-level required parameter indicating as if it should have been set under `spec.initProvider`. 

See related discussion: https://github.com/upbound/provider-azure/issues/535#issuecomment-1709472013

### How can we reproduce it?

Trying to create the following manifest:

```yaml
apiVersion: eventhub.azure.upbound.io/v1beta1
kind: EventHub
metadata:
  name: example-eventhub
spec:
  forProvider: {}
```

Fails with:

```
The EventHub "example-eventhub" is invalid:
* spec: Invalid value: "object": no such key: initProvider evaluating rule: messageRetention is a required parameter
* spec: Invalid value: "object": no such key: initProvider evaluating rule: partitionCount is a required parameter
```
